### ISSUE TITLE
Choose movement technique or maybe combine the two branches in some way.

### ISSUE THREAD

**Issue by 09ejacob** [Malmis1/Recoil-Runner#8]
Compare the two movement test branches and choose which technique to use or maybe combine something from both branches.

**Comment by Malmis1** [comment]
The gradually increasing aircontrol can be great for giving the player more control in the air, especially when descending long distances quickly. I have also written a [comment](https://github.com/Malmis1/Recoil-Runner/issues/7#issuecomment-2402688424) on a certain problem that should in general be fixed which is not addressed yet.

The functionality in the `player-gradually-increase-aircontrol` and `movement-weapon-test` branches can be combined. We can also combine them in such a way that allow us to turn on or off certain features (?). The reset recoil method needs to be reintroduced though since the `movement-weapon-test` branch relies on it.

**Comment by Malmis1** [comment]
I have merged the two branches `player-gradually-increase-aircontrol` and `movement-weapon-test`.
